---
title: "CensusJoin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../"))
library(tidyverse)
library(magrittr)
library(readxl)
library(xlsx)
library(datasets)
library(dplyr)
library(magrittr)
library(markdown)
library(methods)
library(readr)
library(readxl)
library(stringr)
library(tibble)
library(tidyr)

```

Import and tidy SocialExplorer data


```{r, Al to CO}

RelALtoCO <- read_csv("data-raw/States/AltoCO.csv",
                      skip = 1)

for(i in seq(from = 2, to = 939, by = 3)){
  names(RelALtoCO)[i + 1] <- names(RelALtoCO)[i]
  names(RelALtoCO)[i + 2] <- names(RelALtoCO)[i]
}

names(RelALtoCO) <- make.names(names(RelALtoCO), unique = TRUE)

RelALtoCO <- RelALtoCO %>% 
  slice(c(3, 20))
transpose

RelALtoCO <- t(RelALtoCO) %>%
  data.frame() %>% 
  rownames_to_column(var = "county") %>%
  slice(-1) %>% 
  rename(relig = X1, muslim = X2) %>%
  spread(key = relig, value= muslim) %>%
  mutate(county = str_replace_all(county, ".1", "")) %>% 
  mutate(county = str_replace_all(county, ".2", ""))
  


```



```{r, CN to ILL}

RelCNtoILL<- read_excel("data-raw/States/CNtoILL.xlsx", skip = 1, sheet = "Sheet1")

for(i in seq(from = 2, to = 1420, by = 3)){
  names(RelCNtoILL)[i + 1] <- names(RelCNtoILL)[i]
  names(RelCNtoILL)[i + 2] <- names(RelCNtoILL)[i]
}

names(RelCNtoILL) <- make.names(names(RelCNtoILL), unique = TRUE)

RelCNtoILL <- RelCNtoILL %>% 
  slice(c(3, 20))

RelCNtoILL <- t(RelCNtoILL) %>%
   data.frame() %>% 
  rownames_to_column(var = "county") %>%
  slice(-1) %>% 
  rename(relig = X1, muslim = X2) %>%
  spread(key = relig, value= muslim) %>%
  mutate(county = str_replace_all(county, ".1", "")) %>% 
  mutate(county = str_replace_all(county, ".2", "")) 
```

```{r, Indiana to Minnesota}

RelINtoMI<- read_excel("data-raw/States/INtoMI.xlsx", skip = 1, sheet = "Sheet1")

for(i in seq(from = 2, to = 2063, by = 3)){
  names(RelINtoMI)[i + 1] <- names(RelINtoMI)[i]
  names(RelINtoMI)[i + 2] <- names(RelINtoMI)[i]
}

names(RelINtoMI) <- make.names(names(RelINtoMI), unique = TRUE)

RelINtoMI <- RelINtoMI %>% 
  slice(c(3, 20))

RelINtoMI <- t(RelINtoMI) %>%
   data.frame() %>% 
  rownames_to_column(var = "county") %>%
  slice(-1) %>% 
  rename(relig = X1, muslim = X2) %>%
  spread(key = relig, value= muslim) %>%
  mutate(county = str_replace_all(county, ".1", "")) %>% 
  mutate(county = str_replace_all(county, ".2", "")) 

```


```{r, Mississippi to Washingtion}
RelMISStoWA<- read_excel("data-raw/States/MISStoWA.xlsx", skip = 1, sheet = "Sheet1")

for(i in seq(from = 2, to = 5079, by = 3)){
  names(RelMISStoWA)[i + 1] <- names(RelMISStoWA)[i]
  names(RelMISStoWA)[i + 2] <- names(RelMISStoWA)[i]
}

names(RelMISStoWA) <- make.names(names(RelMISStoWA), unique = TRUE)

RelMISStoWA <- RelMISStoWA %>% 
  slice(c(3, 20))

RelMISStoWA <- t(RelMISStoWA) %>%
   data.frame() %>% 
  rownames_to_column(var = "county") %>%
  slice(-1) %>% 
  rename(relig = X1, muslim = X2) %>%
  spread(key = relig, value= muslim) %>%
  mutate(county = str_replace_all(county, ".1", "")) %>% 
  mutate(county = str_replace_all(county, ".2", "")) 

```

```{r, West Virgina to Wyoming}
RelWVtoWY<- read_excel("data-raw/States/WeVtoWY.xlsx", skip = 1, sheet = "Sheet1")

for(i in seq(from = 2, to = 453, by = 3)){
  names(RelWVtoWY)[i + 1] <- names(RelWVtoWY)[i]
  names(RelWVtoWY)[i + 2] <- names(RelWVtoWY)[i]
}

names(RelWVtoWY) <- make.names(names(RelWVtoWY), unique = TRUE)

RelWVtoWY <- RelWVtoWY %>% 
  slice(c(3, 20))

RelWVtoWY <- t(RelWVtoWY) %>%
   data.frame() %>% 
  rownames_to_column(var = "county") %>%
  slice(-1) %>% 
  rename(relig = X1, muslim = X2) %>%
  spread(key = relig, value= muslim) %>%
  mutate(county = str_replace_all(county, ".1", "")) %>% 
  mutate(county = str_replace_all(county, ".2", "")) 

```



```{r, bind}

bind_states <- bind_rows(RelCNtoILL, RelINtoMI, RelMISStoWA, RelWVtoWY, RelALtoCO)

bind_states_sel <- bind_states %>% 
  mutate(Adherents = as.numeric(Adherents)) %>% 
  mutate(Congregations = as.numeric(Congregations)) %>% 
  mutate(Adherents = ifelse(is.na(Adherents), 0, Adherents)) %>% 
  mutate(Congregations = ifelse(is.na(Congregations), 0, Congregations))

bind_states_summ <- bind_states_sel %>% 
  group_by(county) %>% 
  summarize(Adherents = sum(Adherents),
            Congregations = sum(Congregations))
  
bind_state_summ2 <- bind_states_summ %>% #replace(county, "Parish", "County")
  mutate(county = str_replace_all(county, "Parish", "County")) %>%
  mutate(county = str_replace_all(county, "Borough", "County")) %>%
  mutate(county = str_replace_all(county, "Census Area", "County")) %>%
  separate(county, into=c("county", "state"), sep = ".County..") %>% 
  mutate(county = str_replace_all(county, "\\.", " ")) %>%
  mutate(state = str_replace_all(state, "\\.", " "))


```

Load data

```{r}
crime <- read_csv("data-raw/States/CrimeData.csv")
education <-read_csv("data-raw/States/real_education.csv")
population <- read_csv("data-raw/States/real_pop.csv")
income <- read_csv("data-raw/States/Income.csv")
FIPS <- read_csv("data-raw/States/FIPS.csv",
                 skip = 1)

```

```{r}
crime <- crime %>% select(Geo_FIPS, Geo_QName, SE_T003_001)
education <- education %>% select(Geo_FIPS, Geo_QName, SE_T025_001)
population <- population %>% select(Geo_FIPS, Geo_QName, SE_T002_001, SE_T002_002)
income <- income %>% select(Geo_FIPS, Geo_QName, SE_T057_001)


```



```{r}
joined1 <- left_join(x = bind_state_summ2, y = FIPS, 
                     by = c("county" = "County Name" , "state" = "State"))

crime2 <- crime %>%
  mutate(Geo_FIPS = as.character(Geo_FIPS)) %>% 
  mutate(Geo_FIPS2 = ifelse(nchar(Geo_FIPS) == 4,
                           paste0("0", Geo_FIPS),
                           Geo_FIPS))

crime2 <- crime2 %>% separate(Geo_FIPS2, into=c("FIPS State", "FIPS County"), sep = 2, remove = TRUE)
education2 <- education %>% separate(Geo_FIPS, into=c("FIPS State", "FIPS County"), sep = 2, remove = TRUE)
population2 <- population %>% separate(Geo_FIPS, into=c("FIPS State", "FIPS County"), sep = 2, remove = TRUE)
income2 <- income %>% separate(Geo_FIPS, into=c("FIPS State", "FIPS County"), sep = 2, remove = TRUE)




```

```{r, join}
joined2 <- left_join(x = joined1, y = crime2, 
                     by = c("FIPS State" , "FIPS County"))
joined2 <- left_join(x = joined2, y = education2, 
                     by = c("FIPS State" , "FIPS County"))


joined2 <- left_join(x = joined2, y = population2, 
                     by = c("FIPS State" , "FIPS County"))
joined5 <- left_join(x = joined4, y = income2, 
                     by = c("FIPS State" , "FIPS County"))


```


```{r, select}

finalSelect <- joined5 %>% select(county, state, Adherents, Congregations, `FIPS State`, `FIPS County`, Geo_FIPS, SE_T003_001, SE_T025_001, SE_T025_002)

withPop <- left_join(x = finalSelect, y = population2, 
                     by = c("FIPS State" , "FIPS County"))
withPopselect <-withPop %>% select(county, state, Adherents, Congregations, `FIPS State`, `FIPS County`, Geo_FIPS, SE_T003_001, SE_T025_001, SE_T025_002, SE_T002_001, SE_T002_002)

withincome <- left_join(x = withPopselect, y = income2, 
                     by = c("FIPS State" , "FIPS County"))
withincomeselect <- select <-withincome %>% select(county, state, Adherents, Congregations, `FIPS State`, `FIPS County`, Geo_FIPS, SE_T003_001, SE_T025_001, SE_T025_002, SE_T002_001, SE_T002_002, SE_T057_001)
```

```{r, rename}

Neater <- withincomeselect %>% rename(PopOver25 = SE_T025_001, LessThanHS25yrs = SE_T025_002, NumViolentCrime = SE_T003_001, TotalPop = SE_T002_001, PopDens = SE_T002_002, MedIncome = SE_T057_001 ) 
```

```{r}
data.frame()

```

```{r}
write_csv(Neater, "data/Census.csv")

```