---
title: "StateLevel"
output: html_document
---


```{r pressure, echo=FALSE}
knitr::opts_knit$set(root.dir = normalizePath("../"))
library(tidyverse)
library(magrittr)
library(readxl)
library(xlsx)
library(datasets)
library(dplyr)
library(magrittr)
library(markdown)
library(methods)
library(readr)
library(readxl)
library(stringr)
library(tibble)
library(tidyr)

```

```{r, import State Data}

RelState<- read_excel("data-raw/States/Rel_State.xlsx", skip = 1, sheet = "Sheet1")

for(i in seq(from = 2, to =  152, by = 3)){
  names(RelState)[i + 1] <- names(RelState)[i]
  names(RelState)[i + 2] <- names(RelState)[i]
}

names(RelState) <- make.names(names(RelState), unique = TRUE)


RelState <- RelState %>% 
  slice(c(3, 20))

RelState <- t(RelState) %>%
   data.frame() %>%
    rownames_to_column(var = "State") %>%
  slice(-1) %>%
  rename(relig = X1, muslim = X2) %>%
  spread(key = relig, value= muslim) %>%
  mutate(Adherents = as.character(Adherents),
         Congregations = as.character(Congregations)) %>%
  mutate(State = str_replace_all(State, ".1", "")) %>% 
  mutate(State = str_replace_all(State, ".2", ""))


```


Get rid of duplicates...problem with the factor!

```{r}

ReliState2 <- RelState %>% 
  mutate(Adherents = as.numeric(Adherents)) %>% 
  mutate(Congregations = as.numeric(Congregations)) %>% 
  mutate(Adherents = ifelse(is.na(Adherents), 0, Adherents)) %>% 
  mutate(Congregations = ifelse(is.na(Congregations), 0, Congregations)) %>%
  group_by(State) %>% 
  summarize(Adherents = sum(Adherents),
            Congregations = sum(Congregations))


```


```{r, load data}
State_crime <- read_csv("data-raw/States/Crimes_state.csv") %>% mutate(Geo_Name = str_replace_all(Geo_Name, " ", ".")) %>% mutate(Geo_Name = str_replace_all(Geo_Name, "of", "Of"))
ACS <-read_csv("data-raw/States/ACS_State.csv") %>% mutate(Geo_NAME = str_replace_all(Geo_NAME, " ", ".")) %>% mutate(Geo_Name = str_replace_all(Geo_Name, "of", "Of"))

```


```{r, join}

RelACS <- left_join(x = ReliState2, y = ACS, 
                     by = c("State" = "Geo_NAME"))
Reltotal <- left_join(x = RelACS, y = State_crime,
                      by = c("State"= "Geo_Name"))
                     
```                    


```{r, select}

StateCensus <- Reltotal %>% select(State, Adherents, Congregations, Geo_FIPS.x, SE_T025_001, SE_T025_002, SE_T004_001, SE_T002_001, SE_T002_002,  SE_T057_001 )

StateCensus <- StateCensus %>% rename(PopOver25 = SE_T025_001, LessThanHS25yrs = SE_T025_002, NumViolentCrime = SE_T004_001, TotalPop = SE_T002_001, PopDens = SE_T002_002, MedIncome = SE_T057_001 )

```

```{r}
StateCensus <- data.frame(StateCensus, "EducationRatePer100000" = (1 - StateCensus$LessThanHS25yrs/StateCensus$PopOver25)/100000)
StateCensus <- data.frame(StateCensus, "ViolenceRatePer100000" = ( StateCensus$NumViolentCrime/StateCensus$TotalPop)/100000)
StateCensus <- data.frame(StateCensus, "MuslimPopPer100000" = ( StateCensus$Adherents/StateCensus$TotalPop)/100000)


```

```{r}
write_csv(StateCensus, "data/StateCensusTIDY.csv")

```