---
title: "MapPrep"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pressure, echo=FALSE}
library(tidyverse)
library(magrittr)
library(readxl)
library(xlsx)
library(datasets)
library(dplyr)
library(magrittr)
library(markdown)
library(methods)
library(readr)
library(readxl)
library(stringr)
library(tibble)
library(tidyr)

```

```{r, import State Data}

Map_HC<- read_csv("/Users/emilyclark/Desktop/Junior/Math_241/anti-muslim-sentiment/map_HC_stats.csv")
StateCensusTIDY <-read_csv("/Users/emilyclark/Desktop/StateCensusTIDY.csv")
  

```

```{r}

Map_spread <- Map_HC  %>% spread(key = "Year", value = "Year") 
Map_join <- left_join(x = Map_spread, y = StateCensusTIDY, 
                     by = c("State_ID" = "State_ID"))
write_csv(Map_join, "Map_join.csv")
```

```{r}
Map_join2<- read_csv("/Users/emilyclark/Desktop/Map_join2.csv")



```

```{r}

ALL_map <- Map_HC %>% 
  group_by( State_ID) %>% 
  summarise(Muslim_HC = sum(Muslim_HC), General_HC = sum(General_HC))

write_csv(ALL_map, "ALL_map.csv")

```


```{r}
Map_HC_2011 <- Map_HC %>% filter(Year == "2011")
Map_HC_2012 <- Map_HC %>% filter(Year == "2012")
Map_HC_2013 <- Map_HC %>% filter(Year == "2013")

```

```{r}
write_csv(Map_HC_2011, "Map_2011.csv")
write_csv(Map_HC_2012, "Map_2012.csv")
write_csv(Map_HC_2013, "Map_2013.csv")


```